import 'package:cloud_firestore/cloud_firestore.dart';

import '../core/constants.dart';

/// A vehicle whose details are remembered so entry can be one-tap
/// (or one-scan) later. Plate number is the identity key.
class RegisteredVehicle {
  RegisteredVehicle({
    required this.plateNumber,
    required this.driverName,
    required this.vehicleType,
    required this.defaultZoneId,
    required this.registeredAt,
    this.entryCount = 0,
    this.lastSeen,
    this.docId,
    this.driverLicensePhotoPath,
    this.orCrPhotoPath,
    this.driverLicensePhotoUrl,
    this.orCrPhotoUrl,
    this.documentsPath,
    this.documentsUrl,
    this.rfidTag,
    this.points = 0.0,
  });

  final String plateNumber; // normalized, uppercase, spaces preserved
  final String driverName;
  final String vehicleType;
  final String defaultZoneId;
  final DateTime registeredAt;
  final int entryCount;
  final DateTime? lastSeen;
  final String? docId;

  /// RFID card ID — filled either by a plug-and-play USB reader (see
  /// RegisterVehicleScreen's onFieldSubmitted / RfidPointsScreen's
  /// onSubmitted, both of which just listen for the Enter keystroke a
  /// USB-HID reader sends after "typing" the tag) or typed by hand. Null
  /// means this vehicle isn't enrolled in the points program (see
  /// VehicleRegistry.touch / PointsSettingsService).
  final String? rfidTag;

  /// Loyalty points balance — only accrues for vehicles with [rfidTag]
  /// set. See VehicleRegistry.touch for how it's earned and
  /// vehicle_entry_screen.dart's receipt drawer for how it's redeemed.
  /// A double (not an int) since a session can earn a fraction of a
  /// point — see PointsSettingsService.pointsForFee.
  final double points;

  /// Local file paths to each raw captured document photo — fast,
  /// no-network access on whichever device actually captured it, but
  /// meaningless on any other device. Kept around (rather than discarded
  /// once combined) purely so a later retake of just *one* document can
  /// still rebuild [documentsPath] without needing the other document's
  /// image data to already be on this device — see VehicleRegistry.register.
  /// Not shown anywhere directly; [documentsPath]/[documentsUrl] below are
  /// what Vehicle Details actually displays.
  final String? driverLicensePhotoPath;
  final String? orCrPhotoPath;

  /// Firebase Storage download URLs for the raw captures (see
  /// VehicleDocumentStorage) — what lets a *different* device rebuild
  /// [documentsPath] using this document's image even when its local file
  /// only ever existed on the device that captured it.
  final String? driverLicensePhotoUrl;
  final String? orCrPhotoUrl;

  /// The single combined PDF — driver's license then OR/CR, whichever of
  /// the two have actually been captured (see DocumentPdf) — that Vehicle
  /// Details' one "Documents" button opens. Regenerated by
  /// VehicleRegistry.register every time either raw document above
  /// changes, so it's always in sync with them.
  final String? documentsPath;
  final String? documentsUrl;

  /// Search key: uppercase plate with spaces stripped, for exact-match lookup.
  static String normalize(String plate) =>
      plate.replaceAll(RegExp(r'[^A-Za-z0-9]'), '').toUpperCase();

  Map<String, dynamic> toMap() => {
        'plate_number': plateNumber,
        'plate_key': normalize(plateNumber),
        'driver_name': driverName,
        'vehicle_type': vehicleType,
        'default_zone_id': defaultZoneId,
        'registered_at': Timestamp.fromDate(registeredAt),
        'entry_count': entryCount,
        if (lastSeen != null) 'last_seen': Timestamp.fromDate(lastSeen!),
        if (driverLicensePhotoPath != null)
          'driver_license_photo_path': driverLicensePhotoPath,
        if (orCrPhotoPath != null) 'or_cr_photo_path': orCrPhotoPath,
        if (driverLicensePhotoUrl != null)
          'driver_license_photo_url': driverLicensePhotoUrl,
        if (orCrPhotoUrl != null) 'or_cr_photo_url': orCrPhotoUrl,
        if (documentsPath != null) 'documents_path': documentsPath,
        if (documentsUrl != null) 'documents_url': documentsUrl,
        if (rfidTag != null) 'rfid_tag': rfidTag,
        if (rfidTag != null) 'rfid_tag_key': normalize(rfidTag!),
        'points': points,
      };

  factory RegisteredVehicle.fromDoc(DocumentSnapshot doc) {
    final d = doc.data() as Map<String, dynamic>;
    return RegisteredVehicle(
      docId: doc.id,
      plateNumber: d['plate_number'] ?? '',
      driverName: d['driver_name'] ?? '',
      vehicleType: VehicleType.currentLabel(d['vehicle_type'] ?? 'Sedan'),
      defaultZoneId: d['default_zone_id'] ?? '',
      registeredAt:
          (d['registered_at'] as Timestamp?)?.toDate() ?? DateTime.now(),
      entryCount: (d['entry_count'] as num?)?.toInt() ?? 0,
      lastSeen: (d['last_seen'] as Timestamp?)?.toDate(),
      driverLicensePhotoPath: d['driver_license_photo_path'] as String?,
      orCrPhotoPath: d['or_cr_photo_path'] as String?,
      driverLicensePhotoUrl: d['driver_license_photo_url'] as String?,
      orCrPhotoUrl: d['or_cr_photo_url'] as String?,
      documentsPath: d['documents_path'] as String?,
      documentsUrl: d['documents_url'] as String?,
      rfidTag: d['rfid_tag'] as String?,
      points: (d['points'] as num?)?.toDouble() ?? 0.0,
    );
  }
}
