// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      return web;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv0jk5pWwPUbdZmuF6jBduA4882qGArZI',
    appId: '1:326618392344:android:fe30912a12ca4ec58b206d',
    messagingSenderId: '326618392344',
    projectId: 'concepcion-pay-parking',
    storageBucket: 'concepcion-pay-parking.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAES_5aVfKIwrftz1MZnnkoOqXFkDi0XcE',
    appId: '1:326618392344:web:972f71a764e8f6c48b206d',
    messagingSenderId: '326618392344',
    projectId: 'concepcion-pay-parking',
    authDomain: 'concepcion-pay-parking.firebaseapp.com',
    storageBucket: 'concepcion-pay-parking.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAES_5aVfKIwrftz1MZnnkoOqXFkDi0XcE',
    appId: '1:326618392344:web:d2dc5681b604391f8b206d',
    messagingSenderId: '326618392344',
    projectId: 'concepcion-pay-parking',
    authDomain: 'concepcion-pay-parking.firebaseapp.com',
    storageBucket: 'concepcion-pay-parking.firebasestorage.app',
  );
}

