import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'core/responsive.dart';

import 'core/theme.dart';
import 'screens/root_shell.dart';
import 'screens/splash_screen.dart';
import 'services/fee_settings_service.dart';
import 'services/firestore_service.dart';
import 'services/points_settings_service.dart';
import 'widgets/sun_mode.dart';

// Generated by `flutterfire configure` â€” see README.
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  try {
    await YosRepository.instance.init();
  } catch (e) {
    debugPrint('Repository init failed (continuing): $e');
  }
  try {
    await FeeSettingsService.instance.init();
  } catch (e) {
    debugPrint('Fee settings init failed (continuing): $e');
  }
  try {
    await PointsSettingsService.instance.init();
  } catch (e) {
    debugPrint('Points settings init failed (continuing): $e');
  }

  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarIconBrightness: Brightness.dark, // dark icons on light canvas
    statusBarBrightness: Brightness.light, // iOS: light background
  ));
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);

  runApp(const YosApp());
}

class YosApp extends StatelessWidget {
  const YosApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Delivery',
      debugShowCheckedModeBanner: false,
      theme: YosTheme.light(),
      // Applies sun-mode contrast/text-scale overrides to every screen.
      builder: (context, child) =>
          SunModeSwitcher(child: child ?? const SizedBox.shrink()),
      home: StreamBuilder<User?>(
        stream: FirebaseAuth.instance.authStateChanges(),
        builder: (context, snap) {
          if (snap.connectionState == ConnectionState.waiting) {
            return const Scaffold(
              backgroundColor: YosColors.bg,
              body: Center(
                child: CircularProgressIndicator(color: YosColors.accent),
              ),
            );
          }
          // Signed in â†’ dashboard. Otherwise play the cinematic splash,
          // which then hands off to the intro + login flow.
          //
          // isAnonymous is deliberately excluded from "signed in" here:
          // FaceLoginScreen's cross-device cloud fallback (see
          // _tryCloudMatch) briefly signs in anonymously just to satisfy
          // firestore.rules' face_profiles read rule before any real
          // session exists. Since `home` is the root of the whole
          // Navigator, treating that as "signed in" would swap this
          // entire subtree to RootShell and back on every such lookup,
          // tearing down FaceLoginScreen (and its live camera) mid-scan.
          // Keeping the const SplashScreen() instance across that blip
          // means Flutter just updates in place instead of remounting.
          final user = snap.data;
          final signedIn = user != null && !user.isAnonymous;
          return signedIn ? const RootShell() : const SplashScreen();
        },
      ),
    );
  }
}
